# app/config/config.yml

ivory_google_map:
    map:
        # Prefix used for the generation of the map javascript variable
        prefix_javascript_variable: "map_"

        # HTML container ID used for the map container
        html_container: "map_canvas"

        # If this flag is enabled, the map will load asynchronous
        async: false

        # If this flag is enabled, the map will autozoom on the overlays added
        auto_zoom: false

        # Center coordinate of the map
        # If the autozoom flag is enabled, the center is not used
        #center:
            #longitude: 0
            #latitude: 0
            #no_wrap: true

        # Zoom of the map
        # If the autozoom flag is enabled, the zoom is not used
        #zoom: 3

        # Default map type
        # Available map type : hybrid, roadmap, satellite, terrain
        type: "roadmap"

        # Map width
        width: "900px"

        # Map height
        height: "800px"

        # Custom map options
        # By default, there is no map options
        map_options:
            disableDefaultUI: true
            disableDoubleClickZoom: true

        # Custom stylesheet options
        # By default, there is no stylesheet options except width & height
        #stylesheet_options:
            #border: "1px solid #000"
            #background-color: "#fff"

        # google map Api language, default en
        language: pt_BR
