# FOS User
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address:        no-reply@sistema-ntw.ver.tc
        sender_name:    Sistema NTW
    resetting:
        email:
            template: email/password_resetting.email.twig
