<?php

namespace AppBundle\Repository;

/**
 * AffiliatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliatedRepository extends \Doctrine\ORM\EntityRepository
{
}
