<?php

namespace AppBundle\Repository;

/**
 * AffiliatedLaboratoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliatedLaboratoryRepository extends \Doctrine\ORM\EntityRepository
{
}
