<?php

namespace AppBundle\Repository;

/**
 * AgentRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
