<?php

namespace AppBundle\Repository;

/**
 * ConteudoPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteudoPedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
