<?php

namespace AppBundle\Repository;

/**
 * CotacoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotacoesRepository extends \Doctrine\ORM\EntityRepository
{
}
