<?php

namespace AppBundle\Repository;

/**
 * DistributorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributorsRepository extends \Doctrine\ORM\EntityRepository
{
}
