<?php

namespace AppBundle\Repository;

/**
 * LaboratoryShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoryShopRepository extends \Doctrine\ORM\EntityRepository
{
}
