<?php

namespace AppBundle\Repository;

/**
 * LaboratoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoryRepository extends \Doctrine\ORM\EntityRepository
{
	/**
   * Adiciona filtros para selecionar apenas eventos à query.
   * @param QueryBuilder $qb Query inicial.
   * @return QueryBuilder Query com filtros.
   */
  public function addActiveQuery(QueryBuilder $qb = null) {
      $em = $this->getEntityManager();

      if (is_null($qb)) {
          $qb = $em->createQueryBuilder();
      }

      $qb->select(array('l'))
              ->from('AppBundle:Laboratory', 'l');

      return $qb;
  }

	/**
   * Busca eventos a partir de um termo de busca.
   * @param string $search Termo da busca.
   * @param integer $max Número máximo de registros a serem retornados.
   * @param integer $offset Índice inicial dos eventos a serem retornados.
   * @return array Array de eventos.
   */
  public function findLaboratoryByName($search) {
      $qb = $this->addActiveQuery();

      $qb->andWhere(
        $qb->expr()->like($qb->expr()->upper('l.name'), ':search')
      )->setParameter(':search', "%" . strtoupper($search) . "%");
      return $qb->getQuery()->execute();
  }
  
  public function findAllOrderByName(){
    $qb = $this->addActiveQuery();

    $qb->orderBy("l.name");
    $qb->andWhere("l.active = :active")
       ->setParameter("active", 1); 
    return $qb->getQuery()->getResult();
  }

}
