<?php

namespace AppBundle\Repository;

/**
 * LaboratoryAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoryAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
