<?php

namespace AppBundle\Repository;

/**
 * ParcelamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
