<?php

namespace AppBundle\Repository;

/**
 * PedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosRepository extends \Doctrine\ORM\EntityRepository
{

	public function addActiveQuery(QueryBuilder $qb = null) {
		$em = $this->getEntityManager();

		if (is_null($qb)) {
			$qb = $em->createQueryBuilder();
		}

		$qb->select(array('p'))
			->from('AppBundle:Pedido', 'p');

		return $qb;
	}

	public function findAllOrder(){
		$qb = $this->addActiveQuery();
		$qb->orderBy('p.name');
	}

	public function findByUserOrder($user){
		$qb = $this->addActiveQuery();
		$qb->where("p.user = :user")
		   ->setParameter("user", $user);
		$qb->orderBy('p.name');

		return $qb->getQuery()->getResult();
	}


    public function findByLaboratoryAndUser($laboratory, $user){
        $qb = $this->addActiveQuery();
        $qb->join("p.laboratory", "laboratory");
        $qb->where("laboratory = :lab")
            ->setParameter("lab", $laboratory);  

        $qb->andWhere("p.user = :user")
		   ->setParameter("user", $user);
        
        return $qb->getQuery()->getResult();   
    }
}
