<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Adiciona filtros para selecionar apenas eventos à query.
   * @param QueryBuilder $qb Query inicial.
   * @return QueryBuilder Query com filtros.
   */
  public function addActiveQuery(QueryBuilder $qb = null) {
      $em = $this->getEntityManager();

      if (is_null($qb)) {
          $qb = $em->createQueryBuilder();
      }

      $qb->select(array('p'))
              ->from('AppBundle:Product', 'p');

      return $qb;
  }

  /**
   * Busca eventos a partir de um termo de busca.
   * @param string $search Termo da busca.
   * @param integer $max Número máximo de registros a serem retornados.
   * @param integer $offset Índice inicial dos eventos a serem retornados.
   * @return array Array de eventos.
   */
  public function findProductByName($search) {
      $qb = $this->addActiveQuery();

      $qb->andWhere(
        $qb->expr()->like($qb->expr()->upper('p.name'), ':search')
      )->setParameter(':search', "%" . strtoupper($search) . "%");
      return $qb->getQuery()->execute();
  }
    
public function findAllOrderProduct() {
        $qb = $this->addActiveQuery();

        $qb->orderBy("p.name");
        return $qb->getQuery()->getResult();
  }
  
}
