<?php

namespace AppBundle\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopLaboratoryRepository extends \Doctrine\ORM\EntityRepository
{
}
